### PR TITLE
44 create log in page

### PR DESCRIPTION
**Pull request by elhagen13**
Added login page and create account page. In the log in page, it should connect to the database and check to see if the user credentials exist, and then transfer pages. In the create account page, it should check to see if the user credentials already exist, and if they do reject it.

### CODE REVIEW

**Comment by angelika930** [comment]
The login code on the front and backend looks pretty organized!

**Comment by Bdon101** [comment]
Looks good to me.

**Comment by SabaHakimi** [comment]
Changes look good to me.

**Comment by elhagen13** [comment]
5 hours

**Pull request merged**
